/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClassComponent: typeof import('./src/components/ClassComponent.vue')['default']
    ComItem: typeof import('./src/components/ComItem.vue')['default']
    ComponentA: typeof import('./src/components/ComponentA.vue')['default']
    ComponentAsync: typeof import('./src/components/ComponentAsync.vue')['default']
    ComponentAttributes: typeof import('./src/components/ComponentAttributes.vue')['default']
    ComponentB: typeof import('./src/components/ComponentB.vue')['default']
    ComponentManyRootAttributes: typeof import('./src/components/ComponentManyRootAttributes.vue')['default']
    ComponentSlot: typeof import('./src/components/ComponentSlot.vue')['default']
    ComponentSlot2: typeof import('./src/components/ComponentSlot2.vue')['default']
    ComponentSlot3: typeof import('./src/components/ComponentSlot3.vue')['default']
    ComponentVModel: typeof import('./src/components/ComponentVModel.vue')['default']
    ComponentVModelModifier: typeof import('./src/components/ComponentVModelModifier.vue')['default']
    copy: typeof import('./src/components/ComponentAttributes copy.vue')['default']
    DynamicsA: typeof import('./src/components/DynamicsA.vue')['default']
    DynamicsB: typeof import('./src/components/DynamicsB.vue')['default']
    DynamicsC: typeof import('./src/components/DynamicsC.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBut: typeof import('element-plus/es')['ElBut']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    ElTextarea: typeof import('element-plus/es')['ElTextarea']
    Item: typeof import('./src/components/Item.vue')['default']
    KeepComp1: typeof import('./src/components/KeepAlive/KeepComp1.vue')['default']
    KeepComp2: typeof import('./src/components/KeepAlive/KeepComp2.vue')['default']
    LifeCycleChild: typeof import('./src/components/LifeCycleChild.vue')['default']
    ProvideInjectChild: typeof import('./src/components/ProvideInject/ProvideInjectChild.vue')['default']
    ProvideInjectChildDeep: typeof import('./src/components/ProvideInject/ProvideInjectChildDeep.vue')['default']
    RefComponent: typeof import('./src/components/RefComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
